/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { CategoryWhereUniqueInput } from "../../category/base/CategoryWhereUniqueInput";
import { ValidateNested, IsString, IsOptional, IsEnum } from "class-validator";
import { Type } from "class-transformer";
import { OrderCreateNestedManyWithoutPetsInput } from "./OrderCreateNestedManyWithoutPetsInput";
import { IsJSONValue } from "@app/custom-validators";
import { GraphQLJSON } from "graphql-type-json";
import { InputJsonValue } from "../../types";
import { EnumPetStatus } from "./EnumPetStatus";
import { TagCreateNestedManyWithoutPetsInput } from "./TagCreateNestedManyWithoutPetsInput";

@InputType()
class PetCreateInput {
  @ApiProperty({
    required: true,
    type: () => CategoryWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => CategoryWhereUniqueInput)
  @Field(() => CategoryWhereUniqueInput)
  categoryId!: CategoryWhereUniqueInput;

  @ApiProperty({
    required: true,
    type: String,
  })
  @IsString()
  @Field(() => String)
  name!: string;

  @ApiProperty({
    required: false,
    type: () => OrderCreateNestedManyWithoutPetsInput,
  })
  @ValidateNested()
  @Type(() => OrderCreateNestedManyWithoutPetsInput)
  @IsOptional()
  @Field(() => OrderCreateNestedManyWithoutPetsInput, {
    nullable: true,
  })
  orders?: OrderCreateNestedManyWithoutPetsInput;

  @ApiProperty({
    required: true,
  })
  @IsJSONValue()
  @Field(() => GraphQLJSON)
  photoUrls!: InputJsonValue;

  @ApiProperty({
    required: false,
    enum: EnumPetStatus,
  })
  @IsEnum(EnumPetStatus)
  @IsOptional()
  @Field(() => EnumPetStatus, {
    nullable: true,
  })
  status?: "available" | "pending" | "sold" | null;

  @ApiProperty({
    required: false,
    type: () => TagCreateNestedManyWithoutPetsInput,
  })
  @ValidateNested()
  @Type(() => TagCreateNestedManyWithoutPetsInput)
  @IsOptional()
  @Field(() => TagCreateNestedManyWithoutPetsInput, {
    nullable: true,
  })
  tags?: TagCreateNestedManyWithoutPetsInput;
}

export { PetCreateInput as PetCreateInput };
